<!DOCTYPE html>
<!--My Site Home Page-->
<html lang="en-us" class="music">
    <head>
        <meta charset="UTF-8">
        <!-- This Labels the Window/Tab -->
        <title>ARTISTS | thewebbspot.com</title>
        <meta name="author" content="Brandon Webb">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="../CSS/cssstyles.css" type="text/css" rel="stylesheet" media="screen" />
        <meta name="viewport" content="width=device-width, iniHal-scale=1.0, maximum-scale=1.0">
    </head>
    <body>
        <?php include $_SERVER['DOCUMENT_ROOT'] . '/modules/header.php'; ?>

        <div class="musicpages">
            <h1>ARTISTS</h1>
        </div>

        <div class="artistlist">
            <ul class="artistlistitems">
             <li><a href="/sitepages/comingsoon.php">5 Seconds of Summer</a></li>
<li><a href="/sitepages/comingsoon.php">A Great Big World</a></li>
<li><a href="/sitepages/comingsoon.php">A Thousand Horses</a></li>
<li><a href="/sitepages/comingsoon.php">a-ha</a></li>
<li><a href="/sitepages/comingsoon.php">A$AP Rocky</a></li>
<li><a href="/sitepages/comingsoon.php">AC/DC</a></li>
<li><a href="/sitepages/comingsoon.php">Act of Defiance</a></li>
<li><a href="/sitepages/comingsoon.php">Adam Lambert</a></li>
<li><a href="/sitepages/comingsoon.php">Adel Tawil</a></li>
<li><a href="/sitepages/comingsoon.php">Adele</a></li>
<li><a href="/sitepages/comingsoon.php">Admiral Fallow</a></li>
<li><a href="/sitepages/comingsoon.php">Agent Fresco</a></li>
<li><a href="/sitepages/comingsoon.php">Akon</a></li>
<li><a href="/sitepages/comingsoon.php">Alabama Shakes</a></li>
<li><a href="/sitepages/comingsoon.php">Albert Hammond, Jr.</a></li>
<li><a href="/sitepages/comingsoon.php">Alessia Cara</a></li>
<li><a href="/sitepages/comingsoon.php">Alesso</a></li>
<li><a href="/sitepages/comingsoon.php">Alex Clare</a></li>
<li><a href="/sitepages/comingsoon.php">Algiers</a></li>
<li><a href="/sitepages/comingsoon.php">Alicia Keys</a></li>
<li><a href="/sitepages/comingsoon.php">All About Kane</a></li>
<li><a href="/sitepages/comingsoon.php">Alle Farben</a></li>
<li><a href="/sitepages/comingsoon.php">Aloe Blacc</a></li>
<li><a href="/sitepages/comingsoon.php">Alt-J</a></li>
<li><a href="/sitepages/comingsoon.php">Alvvays</a></li>
<li><a href="/sitepages/comingsoon.php">American Authors</a></li>
<li><a href="/sitepages/comingsoon.php">Amina Buddafly</a></li>
<li><a href="/sitepages/comingsoon.php">Amy Helm</a></li>
<li><a href="/sitepages/comingsoon.php">Amy Macdonald</a></li>
<li><a href="/sitepages/comingsoon.php">Amy Winehouse</a></li>
<li><a href="/sitepages/comingsoon.php">Ana Popovic & Milton</a></li>
<li><a href="/sitepages/comingsoon.php">Anderson East</a></li>
<li><a href="/sitepages/comingsoon.php">Andra Day</a></li>
<li><a href="/sitepages/comingsoon.php">Andreas Bourani</a></li>
<li><a href="/sitepages/comingsoon.php">Andrew McMahon in the Wilderness</a></li>
<li><a href="/sitepages/comingsoon.php">Andy Grammer</a></li>
<li><a href="/sitepages/comingsoon.php">Andy T Nick Nixon Band</a></li>
<li><a href="/sitepages/comingsoon.php">Arcade Fire</a></li>
<li><a href="/sitepages/comingsoon.php">Arctic Monkeys</a></li>
<li><a href="/sitepages/comingsoon.php">Ariana Grande</a></li>
<li><a href="/sitepages/comingsoon.php">Ariel Pink</a></li>
<li><a href="/sitepages/comingsoon.php">Art Nation</a></li>
<li><a href="/sitepages/comingsoon.php">Ashley Monroe</a></li>
<li><a href="/sitepages/comingsoon.php">Astrid Williamson</a></li>
<li><a href="/sitepages/comingsoon.php">Atlas Genius</a></li>
<li><a href="/sitepages/comingsoon.php">Atoms For Peace</a></li>
<li><a href="/sitepages/comingsoon.php">Audiogroove</a></li>
<li><a href="/sitepages/comingsoon.php">Audioslave</a></li>
<li><a href="/sitepages/comingsoon.php">Augustines</a></li>
<li><a href="/sitepages/comingsoon.php">Avicii</a></li>
<li><a href="/sitepages/comingsoon.php">Avril Lavigne</a></li>
<li><a href="/sitepages/comingsoon.php">Awaken the Empire</a></li>
<li><a href="/sitepages/comingsoon.php">Awolnation</a></li>
<li><a href="/sitepages/comingsoon.php">Azealia Banks</a></li>
<li><a href="/sitepages/comingsoon.php">B.o.B</a></li>
<li><a href="/sitepages/comingsoon.php">Baauer</a></li>
<li><a href="/sitepages/comingsoon.php">Bachman</a></li>
<li><a href="/sitepages/comingsoon.php">Backyard Babies</a></li>
<li><a href="/sitepages/comingsoon.php">Bad Meets Evil</a></li>
<li><a href="/sitepages/comingsoon.php">Band of Horses</a></li>
<li><a href="/sitepages/comingsoon.php">BANKS</a></li>
<li><a href="/sitepages/comingsoon.php">Barrence Whitfield and the Savages</a></li>
<li><a href="/sitepages/comingsoon.php">Bastille</a></li>
<li><a href="/sitepages/comingsoon.php">Bat for Lashes</a></li>
<li><a href="/sitepages/comingsoon.php">Bea Miller</a></li>
<li><a href="/sitepages/comingsoon.php">Beach House</a></li>
<li><a href="/sitepages/comingsoon.php">Beady Eye</a></li>
<li><a href="/sitepages/comingsoon.php">Beck</a></li>
<li><a href="/sitepages/comingsoon.php">Ben Howard</a></li>
<li><a href="/sitepages/comingsoon.php">Benjamin Booker</a></li>
<li><a href="/sitepages/comingsoon.php">Beyonce</a></li>
<li><a href="/sitepages/comingsoon.php">Big Data</a></li>
<li><a href="/sitepages/comingsoon.php">Big Sean</a></li>
<li><a href="/sitepages/comingsoon.php">Bilderbuch</a></li>
<li><a href="/sitepages/comingsoon.php">Billie Joe + Norah</a></li>
<li><a href="/sitepages/comingsoon.php">Billy Currington</a></li>
<li><a href="/sitepages/comingsoon.php">Birdy</a></li>
<li><a href="/sitepages/comingsoon.php">Biters</a></li>
<li><a href="/sitepages/comingsoon.php">Black Rivers</a></li>
<li><a href="/sitepages/comingsoon.php">Black Star Riders</a></li>
<li><a href="/sitepages/comingsoon.php">Blackwelder</a></li>
<li><a href="/sitepages/comingsoon.php">Blake Shelton</a></li>
<li><a href="/sitepages/comingsoon.php">Bleachers</a></li>
<li><a href="/sitepages/comingsoon.php">Blur</a></li>
<li><a href="/sitepages/comingsoon.php">Blurred Vision</a></li>
<li><a href="/sitepages/comingsoon.php">Bombay Bicycle Club</a></li>
<li><a href="/sitepages/comingsoon.php">Bon Iver</a></li>
<li><a href="/sitepages/comingsoon.php">Bon Jovi</a></li>
<li><a href="/sitepages/comingsoon.php">Bonedog</a></li>
<li><a href="/sitepages/comingsoon.php">Bop English</a></li>
<li><a href="/sitepages/comingsoon.php">Boy</a></li>
<li><a href="/sitepages/comingsoon.php">Brad Paisley</a></li>
<li><a href="/sitepages/comingsoon.php">Brandon Flowers</a></li>
<li><a href="/sitepages/comingsoon.php">Brantley Gilbert</a></li>
<li><a href="/sitepages/comingsoon.php">Breaking Benjamin</a></li>
<li><a href="/sitepages/comingsoon.php">Brent Best</a></li>
<li><a href="/sitepages/comingsoon.php">Brett Eldredge</a></li>
<li><a href="/sitepages/comingsoon.php">Brian Eno & Karl Hyde</a></li>
<li><a href="/sitepages/comingsoon.php">Bridge to Grace</a></li>
<li><a href="/sitepages/comingsoon.php">Bridgit Mendler</a></li>
<li><a href="/sitepages/comingsoon.php">Broken Bells</a></li>
<li><a href="/sitepages/comingsoon.php">BROODS</a></li>
<li><a href="/sitepages/comingsoon.php">Bruce Springsteen</a></li>
<li><a href="/sitepages/comingsoon.php">Bruno Mars</a></li>
<li><a href="/sitepages/comingsoon.php">Buckcherry</a></li>
<li><a href="/sitepages/comingsoon.php">Buena Vista Social Club</a></li>
<li><a href="/sitepages/comingsoon.php">Bullet for My Valentine</a></li>
<li><a href="/sitepages/comingsoon.php">Bully</a></li>
<li><a href="/sitepages/comingsoon.php">Burn Halo</a></li>
<li><a href="/sitepages/comingsoon.php">C Duncan</a></li>
<li><a href="/sitepages/comingsoon.php">Cage the Elephant</a></li>
<li><a href="/sitepages/comingsoon.php">Calvin Harris</a></li>
<li><a href="/sitepages/comingsoon.php">Calvin Harris & Disciples</a></li>
<li><a href="/sitepages/comingsoon.php">Canaan Smith</a></li>
<li><a href="/sitepages/comingsoon.php">Capital Cities</a></li>
<li><a href="/sitepages/comingsoon.php">Caribou</a></li>
<li><a href="/sitepages/comingsoon.php">Carly Rae Jepsen</a></li>
<li><a href="/sitepages/comingsoon.php">Caro Emerald</a></li>
<li><a href="/sitepages/comingsoon.php">Carousel</a></li>
<li><a href="/sitepages/comingsoon.php">Carrie Underwood</a></li>
<li><a href="/sitepages/comingsoon.php">Catfish and the Bottlemen</a></li>
<li><a href="/sitepages/comingsoon.php">Cecile McLorin Salvant</a></li>
<li><a href="/sitepages/comingsoon.php">Cee-Lo Green</a></li>
<li><a href="/sitepages/comingsoon.php">Charli XCX</a></li>
<li><a href="/sitepages/comingsoon.php">Charlie Haden & Gonzalo Rubalcaba</a></li>
<li><a href="/sitepages/comingsoon.php">Chase Rice</a></li>
<li><a href="/sitepages/comingsoon.php">Chelsea Wolfe</a></li>
<li><a href="/sitepages/comingsoon.php">Cher Lloyd</a></li>
<li><a href="/sitepages/comingsoon.php">Cheryl Cole</a></li>
<li><a href="/sitepages/comingsoon.php">Chet Faker</a></li>
<li><a href="/sitepages/comingsoon.php">Chris Brown</a></li>
<li><a href="/sitepages/comingsoon.php">Chris Brown & Tyga</a></li>
<li><a href="/sitepages/comingsoon.php">Chris Caffery</a></li>
<li><a href="/sitepages/comingsoon.php">Chris Stapleton</a></li>
<li><a href="/sitepages/comingsoon.php">Chrissie Hynde</a></li>
<li><a href="/sitepages/comingsoon.php">Christina Aguilera</a></li>
<li><a href="/sitepages/comingsoon.php">Christina Perri</a></li>
<li><a href="/sitepages/comingsoon.php">Christine and the Queens</a></li>
<li><a href="/sitepages/comingsoon.php">Ciara</a></li>
<li><a href="/sitepages/comingsoon.php">Circa Waves</a></li>
<li><a href="/sitepages/comingsoon.php">Clean Bandit</a></li>
<li><a href="/sitepages/comingsoon.php">Coeur De Pirate</a></li>
<li><a href="/sitepages/comingsoon.php">Colbie Caillat</a></li>
<li><a href="/sitepages/comingsoon.php">Cold War Kids</a></li>
<li><a href="/sitepages/comingsoon.php">Coldplay</a></li>
<li><a href="/sitepages/comingsoon.php">Cole Swindell</a></li>
<li><a href="/sitepages/comingsoon.php">Conchita Wurst</a></li>
<li><a href="/sitepages/comingsoon.php">Courtney Barnett</a></li>
<li><a href="/sitepages/comingsoon.php">Crazy Town</a></li>
<li><a href="/sitepages/comingsoon.php">Cro</a></li>
<li><a href="/sitepages/comingsoon.php">D'Angelo and The Vanguard</a></li>
<li><a href="/sitepages/comingsoon.php">Daft Punk</a></li>
<li><a href="/sitepages/comingsoon.php">Dam-Funk</a></li>
<li><a href="/sitepages/comingsoon.php">Damien Rice</a></li>
<li><a href="/sitepages/comingsoon.php">Damn Dice</a></li>
<li><a href="/sitepages/comingsoon.php">Damon Albarn</a></li>
<li><a href="/sitepages/comingsoon.php">Dan + Shay</a></li>
<li><a href="/sitepages/comingsoon.php">Daniel Merriweather</a></li>
<li><a href="/sitepages/comingsoon.php">Daniel Romano</a></li>
<li><a href="/sitepages/comingsoon.php">Darius Rucker</a></li>
<li><a href="/sitepages/comingsoon.php">Daughtry</a></li>
<li><a href="/sitepages/comingsoon.php">David Guetta</a></li>
<li><a href="/sitepages/comingsoon.php">Dawes</a></li>
<li><a href="/sitepages/comingsoon.php">Death Cab for Cutie</a></li>
<li><a href="/sitepages/comingsoon.php">Delta Deep</a></li>
<li><a href="/sitepages/comingsoon.php">Demi Lovato</a></li>
<li><a href="/sitepages/comingsoon.php">Deorro & Chris Brown</a></li>
<li><a href="/sitepages/comingsoon.php">Desmond Dekker</a></li>
<li><a href="/sitepages/comingsoon.php">Diddy - Dirty Money</a></li>
<li><a href="/sitepages/comingsoon.php">Disclosure</a></li>
<li><a href="/sitepages/comingsoon.php">Disturbed</a></li>
<li><a href="/sitepages/comingsoon.php">Django Django</a></li>
<li><a href="/sitepages/comingsoon.php">Don Broco</a></li>
<li><a href="/sitepages/comingsoon.php">Donnie Trumpet & The Social Experiment</a></li>
<li><a href="/sitepages/comingsoon.php">Dornik</a></li>
<li><a href="/sitepages/comingsoon.php">Dotan</a></li>
<li><a href="/sitepages/comingsoon.php">Dr. Dre</a></li>
<li><a href="/sitepages/comingsoon.php">Drake</a></li>
<li><a href="/sitepages/comingsoon.php">Drenge</a></li>
<li><a href="/sitepages/comingsoon.php">Duffy</a></li>
<li><a href="/sitepages/comingsoon.php">Dustin Lynch</a></li>
<li><a href="/sitepages/comingsoon.php">Easton Corbin</a></li>
<li><a href="/sitepages/comingsoon.php">Echosmith</a></li>
<li><a href="/sitepages/comingsoon.php">Ed Sheeran</a></li>
<li><a href="/sitepages/comingsoon.php">Edward Sharpe & The Magnetic Zeros</a></li>
<li><a href="/sitepages/comingsoon.php">Elbow</a></li>
<li><a href="/sitepages/comingsoon.php">Ella Henderson</a></li>
<li><a href="/sitepages/comingsoon.php">Elle King</a></li>
<li><a href="/sitepages/comingsoon.php">Ellie Goulding</a></li>
<li><a href="/sitepages/comingsoon.php">Elvis Costello and The Roots</a></li>
<li><a href="/sitepages/comingsoon.php">Emeli Sande</a></li>
<li><a href="/sitepages/comingsoon.php">Eminem</a></li>
<li><a href="/sitepages/comingsoon.php">Eminem & Linkin Park</a></li>
<li><a href="/sitepages/comingsoon.php">Emmylou Harris & Rodney Crowell</a></li>
<li><a href="/sitepages/comingsoon.php">Empire of the Sun</a></li>
<li><a href="/sitepages/comingsoon.php">End of the Dream</a></li>
<li><a href="/sitepages/comingsoon.php">Eric Church</a></li>
<li><a href="/sitepages/comingsoon.php">Eric Paslay</a></li>
<li><a href="/sitepages/comingsoon.php">Everything Everything</a></li>
<li><a href="/sitepages/comingsoon.php">Ezra Furman</a></li>
<li><a href="/sitepages/comingsoon.php">Fall Out Boy</a></li>
<li><a href="/sitepages/comingsoon.php">Father John Misty</a></li>
<li><a href="/sitepages/comingsoon.php">Fearless Vampire Killers</a></li>
<li><a href="/sitepages/comingsoon.php">Feder</a></li>
<li><a href="/sitepages/comingsoon.php">Feist</a></li>
<li><a href="/sitepages/comingsoon.php">Felix Jaehn</a></li>
<li><a href="/sitepages/comingsoon.php">Fergie</a></li>
<li><a href="/sitepages/comingsoon.php">FFS</a></li>
<li><a href="/sitepages/comingsoon.php">Fidlar</a></li>
<li><a href="/sitepages/comingsoon.php">Fifth Harmony</a></li>
<li><a href="/sitepages/comingsoon.php">Finale</a></li>
<li><a href="/sitepages/comingsoon.php">First Aid Kit</a></li>
<li><a href="/sitepages/comingsoon.php">First Decree</a></li>
<li><a href="/sitepages/comingsoon.php">Fitz and The Tantrums</a></li>
<li><a href="/sitepages/comingsoon.php">Five Finger Death Punch</a></li>
<li><a href="/sitepages/comingsoon.php">FKA twigs</a></li>
<li><a href="/sitepages/comingsoon.php">Fleet Foxes</a></li>
<li><a href="/sitepages/comingsoon.php">Flo Morrissey</a></li>
<li><a href="/sitepages/comingsoon.php">Flo Rida</a></li>
<li><a href="/sitepages/comingsoon.php">Florence and The Machine</a></li>
<li><a href="/sitepages/comingsoon.php">Florida Georgia Line</a></li>
<li><a href="/sitepages/comingsoon.php">Foals</a></li>
<li><a href="/sitepages/comingsoon.php">Foo Fighters</a></li>
<li><a href="/sitepages/comingsoon.php">Fort Minor</a></li>
<li><a href="/sitepages/comingsoon.php">Foster The People</a></li>
<li><a href="/sitepages/comingsoon.php">Frank Carter & The Rattlesnakes</a></li>
<li><a href="/sitepages/comingsoon.php">Frank Ocean</a></li>
<li><a href="/sitepages/comingsoon.php">Frank Turner</a></li>
<li><a href="/sitepages/comingsoon.php">Frankie Valli & The Four Seasons</a></li>
<li><a href="/sitepages/comingsoon.php">Franz Ferdinand</a></li>
<li><a href="/sitepages/comingsoon.php">Fraser A. Gorman</a></li>
<li><a href="/sitepages/comingsoon.php">fun.</a></li>
<li><a href="/sitepages/comingsoon.php">Future</a></li>
<li><a href="/sitepages/comingsoon.php">G.R.L.</a></li>
<li><a href="/sitepages/comingsoon.php">Galantis</a></li>
<li><a href="/sitepages/comingsoon.php">Gary Barlow</a></li>
<li><a href="/sitepages/comingsoon.php">Gaz Coombes</a></li>
<li><a href="/sitepages/comingsoon.php">Gengahr</a></li>
<li><a href="/sitepages/comingsoon.php">George Ezra</a></li>
<li><a href="/sitepages/comingsoon.php">Ghost</a></li>
<li><a href="/sitepages/comingsoon.php">Giorgio Moroder</a></li>
<li><a href="/sitepages/comingsoon.php">Glass Animals</a></li>
<li><a href="/sitepages/comingsoon.php">Gloria</a></li>
<li><a href="/sitepages/comingsoon.php">Gnarls Barkley</a></li>
<li><a href="/sitepages/comingsoon.php">Gorgon City</a></li>
<li><a href="/sitepages/comingsoon.php">Gotye</a></li>
<li><a href="/sitepages/comingsoon.php">Grace Potter</a></li>
<li><a href="/sitepages/comingsoon.php">Gregory Porter</a></li>
<li><a href="/sitepages/comingsoon.php">Grouplove</a></li>
<li><a href="/sitepages/comingsoon.php">Guns N' Roses</a></li>
            </ul>
            <ul class="artistlistitems">
            <li><a href="/sitepages/comingsoon.php">Gwen Stefani</a></li>
<li><a href="/sitepages/comingsoon.php">Gym Class Heroes</a></li>
<li><a href="/sitepages/comingsoon.php">HAIM</a></li>
<li><a href="/sitepages/comingsoon.php">Hair of the Dog</a></li>
<li><a href="/sitepages/comingsoon.php">Halsey</a></li>
<li><a href="/sitepages/comingsoon.php">Herrenmagazin</a></li>
<li><a href="/sitepages/comingsoon.php">Highly Suspect</a></li>
<li><a href="/sitepages/comingsoon.php">Hinder</a></li>
<li><a href="/sitepages/comingsoon.php">Hollis Brown</a></li>
<li><a href="/sitepages/comingsoon.php">Holly Herndon</a></li>
<li><a href="/sitepages/comingsoon.php">Hot Chip</a></li>
<li><a href="/sitepages/comingsoon.php">Hot Roux</a></li>
<li><a href="/sitepages/comingsoon.php">Houndmouth</a></li>
<li><a href="/sitepages/comingsoon.php">Houndstooth</a></li>
<li><a href="/sitepages/comingsoon.php">Hozier</a></li>
<li><a href="/sitepages/comingsoon.php">Hunter Hayes</a></li>
<li><a href="/sitepages/comingsoon.php">I Prevail</a></li>
<li><a href="/sitepages/comingsoon.php">Iamamiwhoami</a></li>
<li><a href="/sitepages/comingsoon.php">Icona Pop</a></li>
<li><a href="/sitepages/comingsoon.php">Iggy Azalea</a></li>
<li><a href="/sitepages/comingsoon.php">Imagine Dragons</a></li>
<li><a href="/sitepages/comingsoon.php">Indiana</a></li>
<li><a href="/sitepages/comingsoon.php">Ingrid Michaelson</a></li>
<li><a href="/sitepages/comingsoon.php">Inna</a></li>
<li><a href="/sitepages/comingsoon.php">Interpol</a></li>
<li><a href="/sitepages/comingsoon.php">Iron and Wine & Ben Bridwell</a></li>
<li><a href="/sitepages/comingsoon.php">Iron Maiden</a></li>
<li><a href="/sitepages/comingsoon.php">Ivy Levan</a></li>
<li><a href="/sitepages/comingsoon.php">J. Cole</a></li>
<li><a href="/sitepages/comingsoon.php">Jac Dalton</a></li>
<li><a href="/sitepages/comingsoon.php">Jack Johnson</a></li>
<li><a href="/sitepages/comingsoon.php">Jack Savoretti</a></li>
<li><a href="/sitepages/comingsoon.php">Jack White</a></li>
<li><a href="/sitepages/comingsoon.php">Jagwar Ma</a></li>
<li><a href="/sitepages/comingsoon.php">Jake Bugg</a></li>
<li><a href="/sitepages/comingsoon.php">James Arthur</a></li>
<li><a href="/sitepages/comingsoon.php">James Bay</a></li>
<li><a href="/sitepages/comingsoon.php">James Blake</a></li>
<li><a href="/sitepages/comingsoon.php">James Blunt</a></li>
<li><a href="/sitepages/comingsoon.php">James Morrison</a></li>
<li><a href="/sitepages/comingsoon.php">Jamie Foxx</a></li>
<li><a href="/sitepages/comingsoon.php">Jamie xx</a></li>
<li><a href="/sitepages/comingsoon.php">Jasmine Cain</a></li>
<li><a href="/sitepages/comingsoon.php">Jasmine Thompson</a></li>
<li><a href="/sitepages/comingsoon.php">Jason Aldean</a></li>
<li><a href="/sitepages/comingsoon.php">Jason Derulo</a></li>
<li><a href="/sitepages/comingsoon.php">Jason Isbell</a></li>
<li><a href="/sitepages/comingsoon.php">Jason Mraz</a></li>
<li><a href="/sitepages/comingsoon.php">Jay-Z</a></li>
<li><a href="/sitepages/comingsoon.php">Jay-Z & Kanye West</a></li>
<li><a href="/sitepages/comingsoon.php">Jay-Z and Linkin Park</a></li>
<li><a href="/sitepages/comingsoon.php">Jennifer Hudson</a></li>
<li><a href="/sitepages/comingsoon.php">Jennifer Lopez</a></li>
<li><a href="/sitepages/comingsoon.php">Jenny Lewis</a></li>
<li><a href="/sitepages/comingsoon.php">Jesse Woods</a></li>
<li><a href="/sitepages/comingsoon.php">Jessie J</a></li>
<li><a href="/sitepages/comingsoon.php">Jessie Ware</a></li>
<li><a href="/sitepages/comingsoon.php">Jill Scott</a></li>
<li><a href="/sitepages/comingsoon.php">Joan Shelley</a></li>
<li><a href="/sitepages/comingsoon.php">John Legend</a></li>
<li><a href="/sitepages/comingsoon.php">John Mayer</a></li>
<li><a href="/sitepages/comingsoon.php">John Newman</a></li>
<li><a href="/sitepages/comingsoon.php">Johnny Marr</a></li>
<li><a href="/sitepages/comingsoon.php">Jonathan Tyler</a></li>
<li><a href="/sitepages/comingsoon.php">Jools Holland & His Rhythm & Blues Orchestra</a></li>
<li><a href="/sitepages/comingsoon.php">Jordin Sparks</a></li>
<li><a href="/sitepages/comingsoon.php">Joris</a></li>
<li><a href="/sitepages/comingsoon.php">Joss Stone</a></li>
<li><a href="/sitepages/comingsoon.php">Joy Williams</a></li>
<li><a href="/sitepages/comingsoon.php">Joywave</a></li>
<li><a href="/sitepages/comingsoon.php">Jungle</a></li>
<li><a href="/sitepages/comingsoon.php">Justin Bieber</a></li>
<li><a href="/sitepages/comingsoon.php">Justin Timberlake</a></li>
<li><a href="/sitepages/comingsoon.php">Kacey Musgraves</a></li>
<li><a href="/sitepages/comingsoon.php">Kadavar</a></li>
<li><a href="/sitepages/comingsoon.php">Kaiser Chiefs</a></li>
<li><a href="/sitepages/comingsoon.php">Kamasi Washington</a></li>
<li><a href="/sitepages/comingsoon.php">Kanye West</a></li>
<li><a href="/sitepages/comingsoon.php">Kasabian</a></li>
<li><a href="/sitepages/comingsoon.php">Katy B</a></li>
<li><a href="/sitepages/comingsoon.php">Katy Perry</a></li>
<li><a href="/sitepages/comingsoon.php">Ke$ha</a></li>
<li><a href="/sitepages/comingsoon.php">Keane</a></li>
<li><a href="/sitepages/comingsoon.php">Kelly Clarkson</a></li>
<li><a href="/sitepages/comingsoon.php">Kelsea Ballerini</a></li>
<li><a href="/sitepages/comingsoon.php">Kendrick Lamar</a></li>
<li><a href="/sitepages/comingsoon.php">Kevin Rudolf</a></li>
<li><a href="/sitepages/comingsoon.php">Kicking Harold</a></li>
<li><a href="/sitepages/comingsoon.php">Kid Ink</a></li>
<li><a href="/sitepages/comingsoon.php">Kid Rock</a></li>
<li><a href="/sitepages/comingsoon.php">Kiesza</a></li>
<li><a href="/sitepages/comingsoon.php">Kim Burrell</a></li>
<li><a href="/sitepages/comingsoon.php">Kings of Leon</a></li>
<li><a href="/sitepages/comingsoon.php">Kip Moore</a></li>
<li><a href="/sitepages/comingsoon.php">Klangkarussell</a></li>
<li><a href="/sitepages/comingsoon.php">Klingande</a></li>
<li><a href="/sitepages/comingsoon.php">Kobra and the Lotus</a></li>
<li><a href="/sitepages/comingsoon.php">Kodaline</a></li>
<li><a href="/sitepages/comingsoon.php">Kongos</a></li>
<li><a href="/sitepages/comingsoon.php">Kovacs</a></li>
<li><a href="/sitepages/comingsoon.php">Krept & Konan</a></li>
<li><a href="/sitepages/comingsoon.php">KT Tunstall</a></li>
<li><a href="/sitepages/comingsoon.php">Kurt Vile</a></li>
<li><a href="/sitepages/comingsoon.php">Kwabs</a></li>
<li><a href="/sitepages/comingsoon.php">LA Priest</a></li>
<li><a href="/sitepages/comingsoon.php">La Roux</a></li>
<li><a href="/sitepages/comingsoon.php">Labrinth</a></li>
<li><a href="/sitepages/comingsoon.php">Lady Antebellum</a></li>
<li><a href="/sitepages/comingsoon.php">Lady Gaga</a></li>
<li><a href="/sitepages/comingsoon.php">Lana Del Rey</a></li>
<li><a href="/sitepages/comingsoon.php">Lana Del Rey vs. Cedric Gervais</a></li>
<li><a href="/sitepages/comingsoon.php">Lance Canales</a></li>
<li><a href="/sitepages/comingsoon.php">Larry Campbell & Teresa Williams</a></li>
<li><a href="/sitepages/comingsoon.php">Laura Marling</a></li>
<li><a href="/sitepages/comingsoon.php">Lauren Daigle</a></li>
<li><a href="/sitepages/comingsoon.php">Lebron</a></li>
<li><a href="/sitepages/comingsoon.php">Led Zeppelin</a></li>
<li><a href="/sitepages/comingsoon.php">Lee Brice</a></li>
<li><a href="/sitepages/comingsoon.php">Leftfield</a></li>
<li><a href="/sitepages/comingsoon.php">Leon Bridges</a></li>
<li><a href="/sitepages/comingsoon.php">Leona Lewis</a></li>
<li><a href="/sitepages/comingsoon.php">Lianne La Havas</a></li>
<li><a href="/sitepages/comingsoon.php">Lifehouse</a></li>
<li><a href="/sitepages/comingsoon.php">Lil Dicky</a></li>
<li><a href="/sitepages/comingsoon.php">Lil Wayne</a></li>
<li><a href="/sitepages/comingsoon.php">Lilly Wood & The Prick & Robin Schulz</a></li>
<li><a href="/sitepages/comingsoon.php">Lily Allen</a></li>
<li><a href="/sitepages/comingsoon.php">Lindemann</a></li>
<li><a href="/sitepages/comingsoon.php">Lindi Ortega</a></li>
<li><a href="/sitepages/comingsoon.php">Lindsey Stirling</a></li>
<li><a href="/sitepages/comingsoon.php">Linkin Park</a></li>
<li><a href="/sitepages/comingsoon.php">Little Big Town</a></li>
<li><a href="/sitepages/comingsoon.php">Little Mix</a></li>
<li><a href="/sitepages/comingsoon.php">Lizz Wright</a></li>
<li><a href="/sitepages/comingsoon.php">LMFAO</a></li>
<li><a href="/sitepages/comingsoon.php">London Grammar</a></li>
<li><a href="/sitepages/comingsoon.php">Lord Huron</a></li>
<li><a href="/sitepages/comingsoon.php">Lorde</a></li>
<li><a href="/sitepages/comingsoon.php">Lost Frequencies</a></li>
<li><a href="/sitepages/comingsoon.php">Lucy Rose</a></li>
<li><a href="/sitepages/comingsoon.php">Luke Bryan</a></li>
<li><a href="/sitepages/comingsoon.php">Lupe Fiasco</a></li>
<li><a href="/sitepages/comingsoon.php">Lykke Li</a></li>
<li><a href="/sitepages/comingsoon.php">Lynch Mob</a></li>
<li><a href="/sitepages/comingsoon.php">M.I.A.</a></li>
<li><a href="/sitepages/comingsoon.php">Mac Demarco</a></li>
<li><a href="/sitepages/comingsoon.php">Macklemore & Ryan Lewis</a></li>
<li><a href="/sitepages/comingsoon.php">Mad Season & Seattle Symphony</a></li>
<li><a href="/sitepages/comingsoon.php">Maddie & Tae</a></li>
<li><a href="/sitepages/comingsoon.php">MAGIC!</a></li>
<li><a href="/sitepages/comingsoon.php">Maitre Gims</a></li>
<li><a href="/sitepages/comingsoon.php">Major Lazer</a></li>
<li><a href="/sitepages/comingsoon.php">Mans Zelmerlow</a></li>
<li><a href="/sitepages/comingsoon.php">Marina & The Diamonds</a></li>
<li><a href="/sitepages/comingsoon.php">Mark Knopfler</a></li>
<li><a href="/sitepages/comingsoon.php">Mark Ronson</a></li>
<li><a href="/sitepages/comingsoon.php">Marlon Roudette</a></li>
<li><a href="/sitepages/comingsoon.php">Maroon 5</a></li>
<li><a href="/sitepages/comingsoon.php">Martin Garrix</a></li>
<li><a href="/sitepages/comingsoon.php">Mary Lambert</a></li>
<li><a href="/sitepages/comingsoon.php">Matchbox Twenty</a></li>
<li><a href="/sitepages/comingsoon.php">Matthew E. White</a></li>
<li><a href="/sitepages/comingsoon.php">Meek Mill</a></li>
<li><a href="/sitepages/comingsoon.php">Meghan Trainor</a></li>
<li><a href="/sitepages/comingsoon.php">Melanie Martinez</a></li>
<li><a href="/sitepages/comingsoon.php">Melody Gardot</a></li>
<li><a href="/sitepages/comingsoon.php">Metallica</a></li>
<li><a href="/sitepages/comingsoon.php">Method Man</a></li>
<li><a href="/sitepages/comingsoon.php">Metro Station</a></li>
<li><a href="/sitepages/comingsoon.php">MGMT</a></li>
<li><a href="/sitepages/comingsoon.php">Michael Buble</a></li>
<li><a href="/sitepages/comingsoon.php">Michael Jackson</a></li>
<li><a href="/sitepages/comingsoon.php">Michael Ray</a></li>
<li><a href="/sitepages/comingsoon.php">Miguel</a></li>
<li><a href="/sitepages/comingsoon.php">Miike Snow</a></li>
<li><a href="/sitepages/comingsoon.php">Mika</a></li>
<li><a href="/sitepages/comingsoon.php">Mike Posner</a></li>
<li><a href="/sitepages/comingsoon.php">Mike Tramp</a></li>
<li><a href="/sitepages/comingsoon.php">Mike Will Made-It</a></li>
<li><a href="/sitepages/comingsoon.php">Miley Cyrus</a></li>
<li><a href="/sitepages/comingsoon.php">Milky Chance</a></li>
<li><a href="/sitepages/comingsoon.php">Miranda Lambert</a></li>
<li><a href="/sitepages/comingsoon.php">Mitch Mann</a></li>
<li><a href="/sitepages/comingsoon.php">MKTO</a></li>
<li><a href="/sitepages/comingsoon.php">Mo Kolours</a></li>
<li><a href="/sitepages/comingsoon.php">Mocky</a></li>
<li><a href="/sitepages/comingsoon.php">Modest Mouse</a></li>
<li><a href="/sitepages/comingsoon.php">Motorhead</a></li>
<li><a href="/sitepages/comingsoon.php">Mr. Probz</a></li>
<li><a href="/sitepages/comingsoon.php">MS MR</a></li>
<li><a href="/sitepages/comingsoon.php">Mumford & Sons</a></li>
<li><a href="/sitepages/comingsoon.php">Muse</a></li>
<li><a href="/sitepages/comingsoon.php">Natalie Imbruglia</a></li>
<li><a href="/sitepages/comingsoon.php">Natalie Prass</a></li>
<li><a href="/sitepages/comingsoon.php">Natasha Bedingfield</a></li>
<li><a href="/sitepages/comingsoon.php">Nate Ruess</a></li>
<li><a href="/sitepages/comingsoon.php">Nathaniel Rateliff & the Night Sweats</a></li>
<li><a href="/sitepages/comingsoon.php">Naughty Boy</a></li>
<li><a href="/sitepages/comingsoon.php">Ne-Yo</a></li>
<li><a href="/sitepages/comingsoon.php">Neil Young & Promise of the Real</a></li>
<li><a href="/sitepages/comingsoon.php">Nelly Furtado</a></li>
<li><a href="/sitepages/comingsoon.php">Neon Trees</a></li>
<li><a href="/sitepages/comingsoon.php">Nero</a></li>
<li><a href="/sitepages/comingsoon.php">Nev Cottee</a></li>
<li><a href="/sitepages/comingsoon.php">New Politics</a></li>
<li><a href="/sitepages/comingsoon.php">New York Rock & Roll Ensemble</a></li>
<li><a href="/sitepages/comingsoon.php">Newman</a></li>
<li><a href="/sitepages/comingsoon.php">Nick Jonas</a></li>
<li><a href="/sitepages/comingsoon.php">Nick Mulvey</a></li>
<li><a href="/sitepages/comingsoon.php">Nickelback</a></li>
<li><a href="/sitepages/comingsoon.php">Nicki Minaj</a></li>
<li><a href="/sitepages/comingsoon.php">Nico & Vinz</a></li>
<li><a href="/sitepages/comingsoon.php">Night Beds</a></li>
<li><a href="/sitepages/comingsoon.php">Noah and the Whale</a></li>
<li><a href="/sitepages/comingsoon.php">Noah Gundersen</a></li>
<li><a href="/sitepages/comingsoon.php">Noel Gallagher's High Flying Birds</a></li>
<li><a href="/sitepages/comingsoon.php">Norah Jones</a></li>
<li><a href="/sitepages/comingsoon.php">Of Monsters and Men</a></li>
<li><a href="/sitepages/comingsoon.php">Oh Wonder</a></li>
<li><a href="/sitepages/comingsoon.php">Olafur Arnalds & Alice Sara Ott</a></li>
<li><a href="/sitepages/comingsoon.php">Olly Murs</a></li>
<li><a href="/sitepages/comingsoon.php">One Direction</a></li>
<li><a href="/sitepages/comingsoon.php">One-Eyed Doll</a></li>
<li><a href="/sitepages/comingsoon.php">OneRepublic</a></li>
<li><a href="/sitepages/comingsoon.php">Owl City</a></li>
<li><a href="/sitepages/comingsoon.php">P!nk</a></li>
<li><a href="/sitepages/comingsoon.php">P. Diddy</a></li>
<li><a href="/sitepages/comingsoon.php">Palma Violets</a></li>
<li><a href="/sitepages/comingsoon.php">Paloma Faith</a></li>
<li><a href="/sitepages/comingsoon.php">Panic! at the Disco</a></li>
<li><a href="/sitepages/comingsoon.php">Paolo Nutini</a></li>
<li><a href="/sitepages/comingsoon.php">Paramore</a></li>
<li><a href="/sitepages/comingsoon.php">Parmalee</a></li>
<li><a href="/sitepages/comingsoon.php">Passenger</a></li>
<li><a href="/sitepages/comingsoon.php">Passion Pit</a></li>
<li><a href="/sitepages/comingsoon.php">Paul Kalkbrenner</a></li>
<li><a href="/sitepages/comingsoon.php">Pentatonix</a></li>
<li><a href="/sitepages/comingsoon.php">Peter Fox</a></li>
<li><a href="/sitepages/comingsoon.php">Peter Sinfield</a></li>
<li><a href="/sitepages/comingsoon.php">Pharrell Williams</a></li>
<li><a href="/sitepages/comingsoon.php">Phillip Phillips</a></li>
<li><a href="/sitepages/comingsoon.php">Phoenix</a></li>
<li><a href="/sitepages/comingsoon.php">Pia Mia</a></li>
<li><a href="/sitepages/comingsoon.php">Pink Floyd</a></li>
<li><a href="/sitepages/comingsoon.php">Pitbull</a></li>
<li><a href="/sitepages/comingsoon.php">Plain White T's</a></li>
<li><a href="/sitepages/comingsoon.php">Pop Evil</a></li>
<li><a href="/sitepages/comingsoon.php">Pops Staples</a></li>
<li><a href="/sitepages/comingsoon.php">Prides</a></li>
<li><a href="/sitepages/comingsoon.php">Prince & 3RDEYEGIRL</a></li>
            </ul>
            <ul class="artistlistitems">
              <li><a href="/sitepages/comingsoon.php">Printer Clips</a></li>
<li><a href="/sitepages/comingsoon.php">PSY</a></li>
<li><a href="/sitepages/comingsoon.php">Public Service Broadcasting</a></li>
<li><a href="/sitepages/comingsoon.php">Pugwash</a></li>
<li><a href="/sitepages/comingsoon.php">Purity Ring</a></li>
<li><a href="/sitepages/comingsoon.php">Pussycat Dolls</a></li>
<li><a href="/sitepages/comingsoon.php">Quinn Sullivan</a></li>
<li><a href="/sitepages/comingsoon.php">R. City</a></li>
<li><a href="/sitepages/comingsoon.php">R5</a></li>
<li><a href="/sitepages/comingsoon.php">Rachel Platten</a></li>
<li><a href="/sitepages/comingsoon.php">Rae Morris</a></li>
<li><a href="/sitepages/comingsoon.php">Rae Sremmurd</a></li>
<li><a href="/sitepages/comingsoon.php">RaeLynn</a></li>
<li><a href="/sitepages/comingsoon.php">Rascal Flatts</a></li>
<li><a href="/sitepages/comingsoon.php">Ratatat</a></li>
<li><a href="/sitepages/comingsoon.php">Ray LaMontagne</a></li>
<li><a href="/sitepages/comingsoon.php">Rayland Baxter</a></li>
<li><a href="/sitepages/comingsoon.php">Razorlight</a></li>
<li><a href="/sitepages/comingsoon.php">Real Estate</a></li>
<li><a href="/sitepages/comingsoon.php">Red Hot Chili Peppers</a></li>
<li><a href="/sitepages/comingsoon.php">Red Sun Rising</a></li>
<li><a href="/sitepages/comingsoon.php">Rend Collective</a></li>
<li><a href="/sitepages/comingsoon.php">Revolution Saints</a></li>
<li><a href="/sitepages/comingsoon.php">Rhiannon Giddens</a></li>
<li><a href="/sitepages/comingsoon.php">Rhodes</a></li>
<li><a href="/sitepages/comingsoon.php">Rihanna</a></li>
<li><a href="/sitepages/comingsoon.php">Rihanna, Kanye West & Paul McCartney</a></li>
<li><a href="/sitepages/comingsoon.php">Rita Ora</a></li>
<li><a href="/sitepages/comingsoon.php">Rival Consoles</a></li>
<li><a href="/sitepages/comingsoon.php">Riverside</a></li>
<li><a href="/sitepages/comingsoon.php">Rixton</a></li>
<li><a href="/sitepages/comingsoon.php">Rizzle Kicks</a></li>
<li><a href="/sitepages/comingsoon.php">Rob Thomas</a></li>
<li><a href="/sitepages/comingsoon.php">Robbie Williams</a></li>
<li><a href="/sitepages/comingsoon.php">Robert Plant & Alison Krauss</a></li>
<li><a href="/sitepages/comingsoon.php">Robin Schulz</a></li>
<li><a href="/sitepages/comingsoon.php">Robin Thicke</a></li>
<li><a href="/sitepages/comingsoon.php">Robyn & La Bagatelle Magique</a></li>
<li><a href="/sitepages/comingsoon.php">Rock Candy Funk Party</a></li>
<li><a href="/sitepages/comingsoon.php">Roger Waters</a></li>
<li><a href="/sitepages/comingsoon.php">Royal Blood</a></li>
<li><a href="/sitepages/comingsoon.php">Royal Headache</a></li>
<li><a href="/sitepages/comingsoon.php">Royksopp & Robyn</a></li>
<li><a href="/sitepages/comingsoon.php">Ruby Amanfu</a></li>
<li><a href="/sitepages/comingsoon.php">Rudimental</a></li>
<li><a href="/sitepages/comingsoon.php">Rumer</a></li>
<li><a href="/sitepages/comingsoon.php">Run the Jewels</a></li>
<li><a href="/sitepages/comingsoon.php">Ryan Adams</a></li>
<li><a href="/sitepages/comingsoon.php">Ryn Weaver</a></li>
<li><a href="/sitepages/comingsoon.php">Saint Asonia</a></li>
<li><a href="/sitepages/comingsoon.php">Sam Hunt</a></li>
<li><a href="/sitepages/comingsoon.php">Sam Outlaw</a></li>
<li><a href="/sitepages/comingsoon.php">Sam Smith</a></li>
<li><a href="/sitepages/comingsoon.php">Sammy Hagar & The Circle</a></li>
<li><a href="/sitepages/comingsoon.php">Santigold</a></li>
<li><a href="/sitepages/comingsoon.php">Sara Bareilles</a></li>
<li><a href="/sitepages/comingsoon.php">Sarah Cracknell</a></li>
<li><a href="/sitepages/comingsoon.php">Savage Garden</a></li>
<li><a href="/sitepages/comingsoon.php">Saving Abel</a></li>
<li><a href="/sitepages/comingsoon.php">SBTRKT</a></li>
<li><a href="/sitepages/comingsoon.php">Scarface</a></li>
<li><a href="/sitepages/comingsoon.php">Scissor Sisters</a></li>
<li><a href="/sitepages/comingsoon.php">Scott Bradlee's Postmodern Jukebox</a></li>
<li><a href="/sitepages/comingsoon.php">Scott Henderson</a></li>
<li><a href="/sitepages/comingsoon.php">Screaming Eagles</a></li>
<li><a href="/sitepages/comingsoon.php">Sean Kingston</a></li>
<li><a href="/sitepages/comingsoon.php">Seether</a></li>
<li><a href="/sitepages/comingsoon.php">Selena Gomez</a></li>
<li><a href="/sitepages/comingsoon.php">Selena Gomez & The Scene</a></li>
<li><a href="/sitepages/comingsoon.php">Seryn</a></li>
<li><a href="/sitepages/comingsoon.php">Seth Avett & Jessica Lea Mayfield</a></li>
<li><a href="/sitepages/comingsoon.php">Sevyn Streeter</a></li>
<li><a href="/sitepages/comingsoon.php">Shakira</a></li>
<li><a href="/sitepages/comingsoon.php">Shamir</a></li>
<li><a href="/sitepages/comingsoon.php">Shane Nicholson</a></li>
<li><a href="/sitepages/comingsoon.php">Shawn Mendes</a></li>
<li><a href="/sitepages/comingsoon.php">Sheppard</a></li>
<li><a href="/sitepages/comingsoon.php">Sia</a></li>
<li><a href="/sitepages/comingsoon.php">Sidewalk Prophets</a></li>
<li><a href="/sitepages/comingsoon.php">Sister Sledge</a></li>
<li><a href="/sitepages/comingsoon.php">Skrillex</a></li>
<li><a href="/sitepages/comingsoon.php">Skrillex & Diplo</a></li>
<li><a href="/sitepages/comingsoon.php">Slash</a></li>
<li><a href="/sitepages/comingsoon.php">Slaves</a></li>
<li><a href="/sitepages/comingsoon.php">Sleaford Mods</a></li>
<li><a href="/sitepages/comingsoon.php">Snow Patrol</a></li>
<li><a href="/sitepages/comingsoon.php">SOAK</a></li>
<li><a href="/sitepages/comingsoon.php">SOHN</a></li>
<li><a href="/sitepages/comingsoon.php">Songhoy Blues</a></li>
<li><a href="/sitepages/comingsoon.php">Southside Johnny & The Asbury Jukes</a></li>
<li><a href="/sitepages/comingsoon.php">Spector</a></li>
<li><a href="/sitepages/comingsoon.php">Spoon</a></li>
<li><a href="/sitepages/comingsoon.php">St. Vincent</a></li>
<li><a href="/sitepages/comingsoon.php">Stacey Solomon</a></li>
<li><a href="/sitepages/comingsoon.php">Stacy Barthe</a></li>
<li><a href="/sitepages/comingsoon.php">Stala & So</a></li>
<li><a href="/sitepages/comingsoon.php">Steve Earle & The Dukes</a></li>
<li><a href="/sitepages/comingsoon.php">Striking Matches</a></li>
<li><a href="/sitepages/comingsoon.php">Stromae</a></li>
<li><a href="/sitepages/comingsoon.php">Swedish House Mafia</a></li>
<li><a href="/sitepages/comingsoon.php">Sylvan Esso</a></li>
<li><a href="/sitepages/comingsoon.php">T-Pain</a></li>
<li><a href="/sitepages/comingsoon.php">T.I.</a></li>
<li><a href="/sitepages/comingsoon.php">Taio Cruz</a></li>
<li><a href="/sitepages/comingsoon.php">Take That</a></li>
<li><a href="/sitepages/comingsoon.php">Talk in Tongues</a></li>
<li><a href="/sitepages/comingsoon.php">Tamaryn</a></li>
<li><a href="/sitepages/comingsoon.php">Tame Impala</a></li>
<li><a href="/sitepages/comingsoon.php">Taylor Swift</a></li>
<li><a href="/sitepages/comingsoon.php">Teenage Time Killers</a></li>
<li><a href="/sitepages/comingsoon.php">Temples</a></li>
<li><a href="/sitepages/comingsoon.php">Terri Lyne Carrington</a></li>
<li><a href="/sitepages/comingsoon.php">Tex Perkins and the Dark Horses</a></li>
<li><a href="/sitepages/comingsoon.php">Thayer Sarrano</a></li>
<li><a href="/sitepages/comingsoon.php">The 1975</a></li>
<li><a href="/sitepages/comingsoon.php">The All-American Rejects</a></li>
<li><a href="/sitepages/comingsoon.php">The Arcs</a></li>
<li><a href="/sitepages/comingsoon.php">The Avener</a></li>
<li><a href="/sitepages/comingsoon.php">The Bad Plus & Joshua Redman</a></li>
<li><a href="/sitepages/comingsoon.php">The Band Perry</a></li>
<li><a href="/sitepages/comingsoon.php">The Betty Fox Band</a></li>
<li><a href="/sitepages/comingsoon.php">The Black Eyed Peas</a></li>
<li><a href="/sitepages/comingsoon.php">The Black Keys</a></li>
<li><a href="/sitepages/comingsoon.php">The Bohicas</a></li>
<li><a href="/sitepages/comingsoon.php">The Chemical Brothers</a></li>
<li><a href="/sitepages/comingsoon.php">The Civil Wars</a></li>
<li><a href="/sitepages/comingsoon.php">The Common Linnets</a></li>
<li><a href="/sitepages/comingsoon.php">The Darkness</a></li>
<li><a href="/sitepages/comingsoon.php">The Dead Daisies</a></li>
<li><a href="/sitepages/comingsoon.php">The Dear Hunter</a></li>
<li><a href="/sitepages/comingsoon.php">The Districts</a></li>
<li><a href="/sitepages/comingsoon.php">The Fratellis</a></li>
<li><a href="/sitepages/comingsoon.php">The Fray</a></li>
<li><a href="/sitepages/comingsoon.php">The Gaslight Anthem</a></li>
<li><a href="/sitepages/comingsoon.php">The Head and the Heart</a></li>
<li><a href="/sitepages/comingsoon.php">The Hunts</a></li>
<li><a href="/sitepages/comingsoon.php">The Jimi Hendrix Experience</a></li>
<li><a href="/sitepages/comingsoon.php">The Kentucky Headhunters with Johnnie Johnson</a></li>
<li><a href="/sitepages/comingsoon.php">The Killers</a></li>
<li><a href="/sitepages/comingsoon.php">The Kooks</a></li>
<li><a href="/sitepages/comingsoon.php">The Longing</a></li>
<li><a href="/sitepages/comingsoon.php">The Lumineers</a></li>
<li><a href="/sitepages/comingsoon.php">The Maccabees</a></li>
<li><a href="/sitepages/comingsoon.php">The Mike Henderson Band</a></li>
<li><a href="/sitepages/comingsoon.php">The Milk Carton Kids</a></li>
<li><a href="/sitepages/comingsoon.php">The Naked and Famous</a></li>
<li><a href="/sitepages/comingsoon.php">The National</a></li>
<li><a href="/sitepages/comingsoon.php">The National Parks</a></li>
<li><a href="/sitepages/comingsoon.php">The Neighbourhood</a></li>
<li><a href="/sitepages/comingsoon.php">The New Basement Tapes</a></li>
<li><a href="/sitepages/comingsoon.php">The Orange Humble Band</a></li>
<li><a href="/sitepages/comingsoon.php">The Paper Kites</a></li>
<li><a href="/sitepages/comingsoon.php">The Piano Guys</a></li>
<li><a href="/sitepages/comingsoon.php">The Pretty Reckless</a></li>
<li><a href="/sitepages/comingsoon.php">The Raconteurs</a></li>
<li><a href="/sitepages/comingsoon.php">The Rubens</a></li>
<li><a href="/sitepages/comingsoon.php">The Script</a></li>
<li><a href="/sitepages/comingsoon.php">The Shins</a></li>
<li><a href="/sitepages/comingsoon.php">The Shires</a></li>
<li><a href="/sitepages/comingsoon.php">The Statesboro Revue</a></li>
<li><a href="/sitepages/comingsoon.php">The Staves</a></li>
<li><a href="/sitepages/comingsoon.php">The Stone Foxes</a></li>
<li><a href="/sitepages/comingsoon.php">The Strokes</a></li>
<li><a href="/sitepages/comingsoon.php">The Strypes</a></li>
<li><a href="/sitepages/comingsoon.php">The Subways</a></li>
<li><a href="/sitepages/comingsoon.php">The Sword</a></li>
<li><a href="/sitepages/comingsoon.php">The Temper Trap</a></li>
<li><a href="/sitepages/comingsoon.php">The Ting Tings</a></li>
<li><a href="/sitepages/comingsoon.php">The V</a></li>
<li><a href="/sitepages/comingsoon.php">The Vaccines</a></li>
<li><a href="/sitepages/comingsoon.php">The Vamps</a></li>
<li><a href="/sitepages/comingsoon.php">The Wanted</a></li>
<li><a href="/sitepages/comingsoon.php">The War On Drugs</a></li>
<li><a href="/sitepages/comingsoon.php">The Weeknd</a></li>
<li><a href="/sitepages/comingsoon.php">The White Stripes</a></li>
<li><a href="/sitepages/comingsoon.php">The Wombats</a></li>
<li><a href="/sitepages/comingsoon.php">The xx</a></li>
<li><a href="/sitepages/comingsoon.php">Them Crooked Vultures</a></li>
<li><a href="/sitepages/comingsoon.php">This Oceanic Feeling</a></li>
<li><a href="/sitepages/comingsoon.php">Thomas Rhett</a></li>
<li><a href="/sitepages/comingsoon.php">Thompson Square</a></li>
<li><a href="/sitepages/comingsoon.php">Three Days Grace</a></li>
<li><a href="/sitepages/comingsoon.php">Timbaland</a></li>
<li><a href="/sitepages/comingsoon.php">Tina Turner</a></li>
<li><a href="/sitepages/comingsoon.php">Tinie Tempah</a></li>
<li><a href="/sitepages/comingsoon.php">Tobias Jesso Jr.</a></li>
<li><a href="/sitepages/comingsoon.php">Todd Terje</a></li>
<li><a href="/sitepages/comingsoon.php">Tom Odell</a></li>
<li><a href="/sitepages/comingsoon.php">Toni Braxton & Babyface</a></li>
<li><a href="/sitepages/comingsoon.php">Tony Bennett & Lady Gaga</a></li>
<li><a href="/sitepages/comingsoon.php">Tony Succar</a></li>
<li><a href="/sitepages/comingsoon.php">Tool</a></li>
<li><a href="/sitepages/comingsoon.php">Tori Kelly</a></li>
<li><a href="/sitepages/comingsoon.php">Torres</a></li>
<li><a href="/sitepages/comingsoon.php">Totally Mild</a></li>
<li><a href="/sitepages/comingsoon.php">Tove Lo</a></li>
<li><a href="/sitepages/comingsoon.php">Tove Styrke</a></li>
<li><a href="/sitepages/comingsoon.php">Train</a></li>
<li><a href="/sitepages/comingsoon.php">Travi$ Scott</a></li>
<li><a href="/sitepages/comingsoon.php">Travie McCoy</a></li>
<li><a href="/sitepages/comingsoon.php">Tremonti</a></li>
<li><a href="/sitepages/comingsoon.php">Trevor Sewell</a></li>
<li><a href="/sitepages/comingsoon.php">Trey Songz</a></li>
<li><a href="/sitepages/comingsoon.php">TV on the Radio</a></li>
<li><a href="/sitepages/comingsoon.php">Tweedy</a></li>
<li><a href="/sitepages/comingsoon.php">Twenty One Pilots</a></li>
<li><a href="/sitepages/comingsoon.php">Two Door Cinema Club</a></li>
<li><a href="/sitepages/comingsoon.php">Tyga</a></li>
<li><a href="/sitepages/comingsoon.php">Tyler Farr</a></li>
<li><a href="/sitepages/comingsoon.php">U2</a></li>
<li><a href="/sitepages/comingsoon.php">Ultimate Painting</a></li>
<li><a href="/sitepages/comingsoon.php">Uncle Acid and The Deadbeats</a></li>
<li><a href="/sitepages/comingsoon.php">United Pursuit</a></li>
<li><a href="/sitepages/comingsoon.php">Unknown Mortal Orchestra</a></li>
<li><a href="/sitepages/comingsoon.php">Usher</a></li>
<li><a href="/sitepages/comingsoon.php">Valerie June</a></li>
<li><a href="/sitepages/comingsoon.php">Vampire Weekend</a></li>
<li><a href="/sitepages/comingsoon.php">Vance Joy</a></li>
<li><a href="/sitepages/comingsoon.php">Viet Cong</a></li>
<li><a href="/sitepages/comingsoon.php">Villagers</a></li>
<li><a href="/sitepages/comingsoon.php">Vince Staples</a></li>
<li><a href="/sitepages/comingsoon.php">Vintage Trouble</a></li>
<li><a href="/sitepages/comingsoon.php">Vivian Green</a></li>
<li><a href="/sitepages/comingsoon.php">Wale</a></li>
<li><a href="/sitepages/comingsoon.php">Walk The Moon</a></li>
<li><a href="/sitepages/comingsoon.php">Warpaint</a></li>
<li><a href="/sitepages/comingsoon.php">Warren Haynes</a></li>
<li><a href="/sitepages/comingsoon.php">Wavves x Cloud Nothings</a></li>
<li><a href="/sitepages/comingsoon.php">Weezer</a></li>
<li><a href="/sitepages/comingsoon.php">White Lies</a></li>
<li><a href="/sitepages/comingsoon.php">Wilco</a></li>
<li><a href="/sitepages/comingsoon.php">Will Butler</a></li>
<li><a href="/sitepages/comingsoon.php">Will Young</a></li>
<li><a href="/sitepages/comingsoon.php">will.i.am</a></li>
<li><a href="/sitepages/comingsoon.php">Willie Nelson & Merle Haggard</a></li>
<li><a href="/sitepages/comingsoon.php">Willis Earl Beal</a></li>
<li><a href="/sitepages/comingsoon.php">Wiz Khalifa</a></li>
<li><a href="/sitepages/comingsoon.php">Wolf Alice</a></li>
<li><a href="/sitepages/comingsoon.php">Wolfmother</a></li>
<li><a href="/sitepages/comingsoon.php">X Ambassadors</a></li>
<li><a href="/sitepages/comingsoon.php">Yael Naim</a></li>
<li><a href="/sitepages/comingsoon.php">Years & Years</a></li>
<li><a href="/sitepages/comingsoon.php">Yo La Tengo</a></li>
<li><a href="/sitepages/comingsoon.php">You+Me</a></li>
<li><a href="/sitepages/comingsoon.php">Young Fathers</a></li>
<li><a href="/sitepages/comingsoon.php">Young Money</a></li>
<li><a href="/sitepages/comingsoon.php">Young The Giant</a></li>
<li><a href="/sitepages/comingsoon.php">Young Thug</a></li>
<li><a href="/sitepages/comingsoon.php">Yusuf/Cat Stevens</a></li>
<li><a href="/sitepages/comingsoon.php">Zac Brown Band</a></li>
            </ul>
        </div>

        <footer>
            <?php include $_SERVER['DOCUMENT_ROOT'] . '/modules/footer.php'; ?>     
        </footer>
    </body>
</html>